guest_list = []
guest_list.append('Jesus')
guest_list.append('Dad')
guest_list.append('Bob')
guest_list.append('Curt')
print('Welcome to dinner, ' + guest_list[0] + '.')
print('Welcome to dinner, ' + guest_list[1] + '.')
print('Welcome to dinner, ' + guest_list[2] + '.')
print('Welcome to dinner, ' + guest_list[3] + '.')
print('Oh, it seems that ' + guest_list[3] + ' can\'t make it.')

guest_list[3] = 'David';
print('New invitation list:')
print('Welcome to dinner, ' + guest_list[0] + '.')
print('Welcome to dinner, ' + guest_list[1] + '.')
print('Welcome to dinner, ' + guest_list[2] + '.')
print('Welcome to dinner, ' + guest_list[3] + '.')

print('Bigger dinner table? Cool!')
guest_list.insert(0, 'God')
guest_list.insert(2, 'Holy Spirit')
guest_list.append('Thomas')
print('Welcome to dinner, ' + guest_list[0] + '.')
print('Welcome to dinner, ' + guest_list[1] + '.')
print('Welcome to dinner, ' + guest_list[2] + '.')
print('Welcome to dinner, ' + guest_list[3] + '.')
print('Welcome to dinner, ' + guest_list[4] + '.')
print('Welcome to dinner, ' + guest_list[5] + '.')
print('Welcome to dinner, ' + guest_list[6] + '.')

